<h1>Week 5</h1>
<h2>Term Structure Models 1</h2>

In [1]:
from models import *
import numpy as np

In [2]:
shortRateModel = shortRate(10, 0.05, 1.1, 0.9)
shortRateModel.printTree()

[0.05 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ] 

[0.045 0.055 0.    0.    0.    0.    0.    0.    0.    0.    0.   ] 

[0.0405 0.0495 0.0605 0.     0.     0.     0.     0.     0.     0.
 0.    ] 

[0.03645 0.04455 0.05445 0.06655 0.      0.      0.      0.      0.
 0.      0.     ] 

[0.032805 0.040095 0.049005 0.059895 0.073205 0.       0.       0.
 0.       0.       0.      ] 

[0.0295245 0.0360855 0.0441045 0.0539055 0.0658845 0.0805255 0.
 0.        0.        0.        0.       ] 

[0.02657205 0.03247695 0.03969405 0.04851495 0.05929605 0.07247295
 0.08857805 0.         0.         0.         0.        ] 

[0.02391485 0.02922926 0.03572465 0.04366346 0.05336645 0.06522566
 0.07972025 0.09743586 0.         0.         0.        ] 

[0.02152336 0.02630633 0.03215218 0.03929711 0.0480298  0.05870309
 0.07174822 0.08769227 0.10717944 0.         0.        ] 

[0.01937102 0.0236757  0.02893696 0.0353674  0.04322682 0.05283278
 0.0645734  0.07892304 0.0964615  0.11789738 0.       

<h2>Question 1</h2>

In [3]:
zcbModel = bond(10, shortRateModel, 0.5, 0.5, 100, 0)
zcbModel.printTree()

[61.62195812  0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.        ] 

[67.44102962 61.96508242  0.          0.          0.          0.
  0.          0.          0.          0.          0.        ] 

[72.8818303  68.06992161 62.6764023   0.          0.          0.
  0.          0.          0.          0.          0.        ] 

[77.88686151 73.78022735 69.09853811 63.83811117  0.          0.
  0.          0.          0.          0.          0.        ] 

[82.42221636 79.02945886 75.10481409 70.61709293 65.55598201  0.
  0.          0.          0.          0.          0.        ] 

[86.47456207 83.77759226 80.61869778 76.95195323 72.7414542  67.96856115
  0.          0.          0.          0.          0.        ] 

[90.04745952 88.00790104 85.59359608 82.75509419 79.4450793  75.62289779
 71.26062925  0.          0.          0.          0.        ] 

[93.15753262 91.72287761 90.00938088 87.97292426 85.56698264 82.74473475
 79.4622

<h2>Question 2</h2>

In [4]:
forwardModel = forward(zcbModel, 4)
forwardModel.printTree()
forwardModel.price()

[61.62195812  0.          0.          0.          0.        ] 

[67.44102962 61.96508242  0.          0.          0.        ] 

[72.8818303  68.06992161 62.6764023   0.          0.        ] 

[77.88686151 73.78022735 69.09853811 63.83811117  0.        ] 

[82.42221636 79.02945886 75.10481409 70.61709293 65.55598201] 

74.88484493844841


<h2>Question 3</h2>

In [5]:
futuresModel = futures(zcbModel, 4)
futuresModel.printTree()
futuresModel.price()

[74.82458063  0.          0.          0.          0.        ] 

[76.93026602 72.71889524  0.          0.          0.        ] 

[78.89648704 74.96404499 70.47374549  0.          0.        ] 

[80.72583761 77.06713648 72.86095351 68.08653747  0.        ] 

[82.42221636 79.02945886 75.10481409 70.61709293 65.55598201] 

74.82458063139569


<h2>Question 4</h2>

In [6]:
optionsModel = option(zcbModel, 6, 80, 1, 1)
optionsModel.printTree()
optionsModel.price()

[2.35721516 0.         0.         0.         0.         0.
 0.        ] 

[3.39350009 1.55665175 0.         0.         0.         0.
 0.        ] 

[4.64733524 2.44507995 0.83945526 0.         0.         0.
 0.        ] 

[6.03029794 3.64080669 1.49141612 0.28906847 0.         0.
 0.        ] 

[7.42283086 5.07737375 2.5286355  0.61661196 0.         0.
 0.        ] 

[8.76878625 6.5638874  3.9980147  1.30708787 0.         0.
 0.        ] 

[10.04745952  8.00790104  5.59359608  2.75509419  0.          0.
  0.        ] 

2.35721516382906


<h2>Question 5</h2>

In [7]:
swapModel = swap(1, 10, 0.5, 0.5, 0.045, shortRateModel, 1000000)
swapModel.printTree()
swapModel.price()

[0.03337424 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ] 

[-0.00226851  0.07235442  0.          0.          0.          0.
  0.          0.          0.          0.          0.        ] 

[-0.03483091  0.03008972  0.1025781   0.          0.          0.
  0.          0.          0.          0.          0.        ] 

[-0.05929641 -0.00418671  0.05834504  0.12822312  0.          0.
  0.          0.          0.          0.          0.        ] 

[-0.07568293 -0.0301326   0.02228614  0.0818577   0.14855504  0.
  0.          0.          0.          0.          0.        ] 

[-0.08423175 -0.04770966 -0.00516187  0.04390843  0.09982271  0.16262731
  0.          0.          0.          0.          0.        ] 

[-0.08535465 -0.05713164 -0.02390194  0.01491387  0.0598258   0.11120415
  0.16919076  0.          0.          0.          0.        ] 

[-0.07958282 -0.05880668 -0.03412143 -0.00496807  0.029213    0.06894138
  0.11463961  0.166

<h2>Question 6</h2>

In [8]:
swaptionModel = swaption(swapModel, 0, 5)
swaptionModel.printTree()
swaptionModel.price()

[0.02631108 0.         0.         0.         0.         0.        ] 

[0.01417813 0.04107514 0.         0.         0.         0.        ] 

[0.00481403 0.02481825 0.0618503  0.         0.         0.        ] 

[0.         0.010018   0.0420755  0.08910898 0.         0.        ] 

[0.         0.         0.02092861 0.06780442 0.12227394 0.        ] 

[0.         0.         0.         0.04390843 0.09982271 0.16262731] 

26311.07949019227
